package com.dedtsss.catawg.core.protocol

import com.dedtsss.catawg.core.configurator.ConfigProtocol
import com.dedtsss.catawg.core.configurator.PublicConfigProfile
import com.dedtsss.catawg.core.diagnostics.DiagnosticEvent
import com.dedtsss.catawg.core.diagnostics.Incident
import java.time.Instant
import kotlinx.serialization.Serializable

/** Shared client/server contract. All timestamps are RFC3339 UTC strings generated by Instant. */
object CatProtocolV1 {
    const val SCHEMA_VERSION = "cat.v1"
    const val API_PREFIX = "/api/v1"
    const val HEALTH = "$API_PREFIX/health"
    const val CAPABILITIES = "$API_PREFIX/capabilities"
    const val DIAGNOSTIC_EVENTS = "$API_PREFIX/diagnostics/events"
    const val INCIDENTS = "$API_PREFIX/incidents"
    const val DIAGNOSTIC_BUNDLE = "$API_PREFIX/diagnostics/bundle"
    const val CONFIG_VALIDATE = "$API_PREFIX/config/validate"
    const val AI_CHAT = "$API_PREFIX/ai/chat"
}

@Serializable
data class EngineCapability(val supported: Boolean, val version: String? = null)

@Serializable
data class ServerFeatures(
    val diagnostics: Boolean = false,
    val configManagement: Boolean = false,
    val serverRouting: Boolean = false,
    val aiGateway: Boolean = false,
)

@Serializable
data class ServerCapabilities(
    val schemaVersion: String = CatProtocolV1.SCHEMA_VERSION,
    val serverId: String,
    val agentVersion: String,
    val os: String,
    val architecture: String,
    val engines: Map<String, EngineCapability>,
    val features: ServerFeatures,
    val managementApiVersion: String,
)

@Serializable
data class CatHealth(
    val schemaVersion: String = CatProtocolV1.SCHEMA_VERSION,
    val status: String,
    val at: String = Instant.now().toString(),
)

@Serializable
data class ConfigValidationRequest(
    val schemaVersion: String = CatProtocolV1.SCHEMA_VERSION,
    val protocol: ConfigProtocol,
    /** Caller must use the separately protected delivery path for secret-bearing configuration. */
    val publicProfile: PublicConfigProfile,
)

@Serializable
data class TimeRange(val from: String, val to: String)

/**
 * Implementations use token-over-TLS after pairing for MVP. The interface intentionally contains
 * no provider/API secret and can later be backed by device credentials or mTLS.
 */
interface CatServerClient {
    suspend fun health(): CatHealth

    suspend fun capabilities(): ServerCapabilities

    suspend fun postDiagnosticEvents(events: List<DiagnosticEvent>)

    suspend fun incidents(range: TimeRange): List<Incident>

    suspend fun diagnosticBundle(range: TimeRange): ByteArray

    suspend fun validateConfig(request: ConfigValidationRequest): String

    suspend fun aiChat(request: CatAiChatRequest): CatAiChatResponse?
}

@Serializable
data class CatAiChatRequest(
    val schemaVersion: String = CatProtocolV1.SCHEMA_VERSION,
    val message: String,
    val model: String? = null,
    val memoryEnabled: Boolean = false,
)

@Serializable
data class CatAiChatResponse(val message: String, val recommendations: List<String> = emptyList())

/** Test/demonstration client; it keeps data locally and is deliberately incapable of secret egress. */
class InMemoryCatServerClient(
    private val advertisedCapabilities: ServerCapabilities =
        ServerCapabilities(
            serverId = "local-mock",
            agentVersion = "0",
            os = "mock",
            architecture = "mock",
            engines =
                mapOf(
                    "wireguard" to EngineCapability(true),
                    "awg2" to EngineCapability(true),
                    "awg3" to EngineCapability(false),
                ),
            features = ServerFeatures(diagnostics = true),
            managementApiVersion = "v1",
        ),
) : CatServerClient {
    private val recordedEvents = mutableListOf<DiagnosticEvent>()
    private val recordedIncidents = mutableListOf<Incident>()

    override suspend fun health() = CatHealth(status = "ok")

    override suspend fun capabilities() = advertisedCapabilities

    override suspend fun postDiagnosticEvents(events: List<DiagnosticEvent>) {
        recordedEvents += events
    }

    override suspend fun incidents(range: TimeRange): List<Incident> = recordedIncidents.toList()

    override suspend fun diagnosticBundle(range: TimeRange): ByteArray = ByteArray(0)

    override suspend fun validateConfig(request: ConfigValidationRequest): String =
        if (request.publicProfile.validation.isValid) "valid" else "invalid"

    override suspend fun aiChat(request: CatAiChatRequest): CatAiChatResponse? = null
}
